<div style="color:#FFFFFF;background-color:Red;text-align:center;padding-top: 50px; padding-right: 30px; padding-bottom: 50px; padding-left: 80px;border-radius:10px 10px 10px 10px;">
    <h1>
        Assignment 5: Logistic Regression On Donor Choose
    </h1>
</div>

<h2 style="color:#C00000;"> 1.1 Business Problem </h2>

<h2 style="color:#C00000;"> 1.1.1 About DonorChoose </h2>

<p style="color:gray";> 
DonorsChoose is a United States-based non-profit organization that allows individuals to donate directly to public school classroom projects. The organization has been given Charity Navigator’s highest rating every year since 2005. In January 2018, they announced that 1 million projects had been funded.
</p>
<hr>

<p style="color:gray";> 
At <a href="www.donorschoose.org"> Donorchoose.org </a>, educators propose an idea for a student project by writing a brief essay and completing some simple forms. Volunteers screen proposals to ensure that projects will directly serve students and to confirm the cost and availability of the resources that the educator requests.Then, individuals from across the nation can review and choose to fund the proposal(s) they find most compelling.
</p>

<hr>

<h2 style="color:#C00000;"> 1.2 Data Overview</h2>

<b>About the Dataset :</b> The dataset consist of two parts :

- train.csv : Contains the Training set
- resources.csv : Contains the resources requested by each proposal
Kaggle Link : https://www.kaggle.com/c/donorschoose-application-screening

<h2 style="color:#C00000;"> 1.3 Mapping ML Problem</h2>

1. It's a classification problem: Given a proposal classify weather project will be recive good funding or not
2. Metrics: Accuracy, and Some sense Interpretability
3. No latancy constraints as such

<div style="color:#FFFFFF;background-color:Red;text-align:center;padding-top: 50px; padding-right: 30px; padding-bottom: 50px; padding-left: 80px;border-radius:10px 10px 10px 10px;">
    <h1>
        2. Preprocessing I: Cleaning and Organizing
    </h1>
</div>

<h2 style="color:#C00000;"> 2.1 Data Preprocessing</h2>
<hr>

<h4 syle="color:gray;"> 
<a href="https://medium.com/@rajneeshjha9s/naive-bayes-model-on-donorschoose-dataset-547302bc1fd3"> All the Data Preprocessing Done by Mr. Rajneesh Jha, We will use it directly here </a> </h4>

In [1]:
#Try yourself for practice, the preprocessing is very similar to Amazon fine food review

<h2 style="color:#C00000;"> 2.2 Text Preprocessing: Cleaning </h2>
<h3 style="color:#C00000;"> 2.2.1 Preprocessing Essay</h3>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Try all these on google colab then download the notebook for revision-

In [4]:
#

<div style="color:#FFFFFF;background-color:Red;text-align:center;padding-top: 50px; padding-right: 30px; padding-bottom: 50px; padding-left: 80px;border-radius:10px 10px 10px 10px;">
    <h1>
        3. Featurizing, Organizing and Splitting 
    </h1>
</div>

Cleaning and Featurizing Should be diffent because we try multiple feturization, techniques and strategies for Improvements

<h3 style="color:#C00000;"> 3 Loading Preprocessed Data </h3>

In [2]:
#1. Loading cleaned data

df = pd.read_csv(r"C:\Users\Faizan_Shakeel\Desktop\Notebooks\Module 3\M302 KNN Code and Assignment\Preprocessed_DonorsChoose_dataset.csv")
print("Data Shape: ", df.shape)
print("Data Columns: ", df.columns)
df.head(2)

Data Shape:  (109248, 14)
Data Columns:  Index(['id', 'teacher_prefix', 'school_state', 'project_grade_category',
       'project_subject_categories', 'project_subject_subcategories',
       'teacher_number_of_previously_posted_projects', 'project_is_approved',
       'price', 'quantity', 'cleaned_titles', 'cleaned_essays',
       'cleaned_summary', 'isdigit_summary'],
      dtype='object')

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
0,p253737,mrs,in,grades_prek_2,literacy_language,esl_literacy,0,0,154.6,23,educational support english learners home,students english learners working english seco...,students_need_opportunities_practice_beginning...,0
1,p258326,mr,fl,grades_6_8,history_civics_health_sports,civics_government_teamsports,7,1,299.0,1,wanted projector hungry learners,students arrive school eager learn polite gene...,students_need_projector_help_viewing_education...,0

In [3]:
# Using 40 % of data for my analysis

X = df.sample(frac=0.4)
X.shape

(43699, 14)

In [4]:
#splitting x and y

y= X['project_is_approved']
X.drop(columns=['project_is_approved'], inplace=True )

#2 Checking features     
print(X.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43699 entries, 28413 to 34777
Data columns (total 13 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            43699 non-null  object
 1   teacher_prefix                                43699 non-null  object
 2   school_state                                  43699 non-null  object
 3   project_grade_category                        43699 non-null  object
 4   project_subject_categories                    43699 non-null  object
 5   project_subject_subcategories                 43699 non-null  object
 6   teacher_number_of_previously_posted_projects  43699 non-null  int64
 7   price                                         43699 non-null  float64
 8   quantity                                      43699 non-null  int64
 9   cleaned_titles                                43684 non-null  object
 10  cleaned_essays                                43699 non-null  object
 11  cleaned_summary                               43699 non-null  object
 12  isdigit_summary                               43699 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 4.7+ MB
None

In [5]:
#3. isnpecting features one by one
a= X.columns[3]

print(a,":", X[a].dtype)
print("Carinality: ", X[a].nunique())

print('Null value count: ',X[a].isnull().sum())
print(X[a].value_counts())

project_grade_category : object
Carinality:  4
Null value count:  0
grades_prek_2    17689
grades_3_5       14913
grades_6_8        6712
grades_9_12       4385
Name: project_grade_category, dtype: int64

<div style="color:gray">
<b> Feature inspection summary </b> <br>
Numerical Columns: ['teacher_number_of_previously_posted_projects', 'project_is_approved', 'price', 'quantity', 'isdigit_summary']<br>
Categorical Columns: ['teacher_prefix', 'school_state', 'project_grade_category', 'project_subject_categories', 'project_subject_subcategories']<br>
Cardinality considerd for encoding: 401 ('project_subject_subcategories')
    
</div>

<h3 style="color:#C00000;"> 3.0 Spliting test train before featurizing </h3>

- In order to avoid data leakage problem

In [6]:
from sklearn.model_selection import train_test_split

#Train Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#From train,train and cv 
X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size=0.3, random_state=42)


print('Train data shape: ', X_train.shape , y_train.shape)
print('Cross valid. shape: ', X_cv.shape , y_cv.shape)
print('Test data shape: ', X_test.shape , y_test.shape)

Train data shape:  (21412, 13) (21412,)
Cross valid. shape:  (9177, 13) (9177,)
Test data shape:  (13110, 13) (13110,)

In [7]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(sampling_strategy='minority', random_state=42)
X_train, y_train = ros.fit_resample(X_train, y_train)


print(y_train.value_counts())
print(X_train.shape)

1    18165
0    18165
Name: project_is_approved, dtype: int64
(36330, 13)

<h3 style="color:#C00000;"> 3.1 Handling Numarical features</h3>

In [8]:
# 1 Getting list of numarical features
def get_numerical_columns(df):
    numerical_cols = []
    for col in df.columns:
        if df[col].dtype in ['int64', 'float64']:
            numerical_cols.append(col)
    return numerical_cols

num_cols= get_numerical_columns(X_train)
print(num_cols)

['teacher_number_of_previously_posted_projects', 'price', 'quantity', 'isdigit_summary']

In [ ]:
#2 Inspecting features,stats, distribution one by one 
a= num_cols[0]
print(a)

feature= X_train[a]
print("Null Values:",feature.isnull().sum())
print(feature.describe())

sns.kdeplot(feature, gridsize=200)
plt.show()

<h4 style="color:#C00000;"> 3.1 [A] min-max scaling</h4>

In [23]:
#3. min-max scaling chosen for now
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train[num_cols]= scaler.fit_transform(X_train[num_cols])           #scaling X_train
X_test[num_cols]= scaler.fit_transform(X_test[num_cols])             #scaling X_test
X_cv[num_cols]= scaler.fit_transform(X_cv[num_cols])             #scaling X_test

print(X_train.shape)
print(X_test.shape)
print(X_cv.shape)

X_cv.head(2)

(36326, 13)
(13110, 13)
(9177, 13)

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
37085,p081091,ms,or,grades_3_5,literacy_language_math_science,literacy_mathematics,0.000000,0.002905,0.066038,get strong get smart exercise balls,4th grade classroom place inquiry thoughtful d...,students_need_swiss_stability_balls_help_impro...,0.0
96539,p097661,mrs,ca,grades_6_8,literacy_language,literacy,0.002404,0.001430,0.139151,learning world problems malala,school consists diverse population students va...,students_need_60_copies_malala_young_reader_ed...,1.0

<h3 style="color:#C00000;"> 3.2 Handling Categorical features</h3>

In [25]:
def column_info(df):
    """
    This function gives following information about all the column 
    column Name: datatypes of column: Carinatity-value
    """
    for col in df.columns:
        print(f"{col} : {df[col].dtype} : Cardinatilty- {df[col].nunique()}")
    
    
column_info(X_test)

id : object : Cardinatilty- 13110
teacher_prefix : object : Cardinatilty- 5
school_state : object : Cardinatilty- 51
project_grade_category : object : Cardinatilty- 4
project_subject_categories : object : Cardinatilty- 46
project_subject_subcategories : object : Cardinatilty- 306
teacher_number_of_previously_posted_projects : float64 : Cardinatilty- 221
price : float64 : Cardinatilty- 9604
quantity : float64 : Cardinatilty- 191
cleaned_titles : object : Cardinatilty- 12175
cleaned_essays : object : Cardinatilty- 13098
cleaned_summary : object : Cardinatilty- 13089
isdigit_summary : float64 : Cardinatilty- 2

In [27]:
#1 Geting list of categorical columns (<405 value_counts)
def get_categorical_columns(df):
    cat_cols = []
    for col in df.columns:
        if df[col].nunique() < 405 and df[col].dtype == 'O':
            cat_cols.append(col)
    return cat_cols



cat_cols = get_categorical_columns(X_train)
print(cat_cols)

['teacher_prefix', 'school_state', 'project_grade_category', 'project_subject_categories', 'project_subject_subcategories']

#### pd.get_dummies()  is not returning same size so using countvectorizer fitting over X_train

In [28]:
X_train.columns

Index(['id', 'teacher_prefix', 'school_state', 'project_grade_category',
       'project_subject_categories', 'project_subject_subcategories',
       'teacher_number_of_previously_posted_projects', 'price', 'quantity',
       'cleaned_titles', 'cleaned_essays', 'cleaned_summary',
       'isdigit_summary'],
      dtype='object')

In [32]:
#Encoding 'teacher_prefix'
#['teacher_prefix', 'school_state', 'project_grade_category', 'project_subject_categories', 'project_subject_subcategories']
from sklearn.feature_extraction.text import CountVectorizer
vectorizor_tp=  CountVectorizer()
vectorizor_tp.fit(X_train['teacher_prefix'].values)  #has fit on train data only

#tranforming train, test, cv
X_train_teacher_prefix = vectorizor_tp.transform(X_train['teacher_prefix'].values)
X_test_teacher_prefix = vectorizor_tp.transform(X_test['teacher_prefix'].values)
X_cv_teacher_prefix = vectorizor_tp.transform(X_cv['teacher_prefix'].values)

print('After Transformation(Encoding)- teacher_prefix')
print(X_train_teacher_prefix.shape)
print(X_test_teacher_prefix.shape)
print(X_cv_teacher_prefix.shape)


##################################################
#Encoding 'school_state''
vectorizor_ss=  CountVectorizer()
vectorizor_ss.fit(X_train['school_state'].values)  #has fit on train data only

#tranforming train, test, cv
X_train_school_state = vectorizor_ss.transform(X_train['school_state'].values)
X_test_school_state = vectorizor_ss.transform(X_test['school_state'].values)
X_cv_school_state = vectorizor_ss.transform(X_cv['school_state'].values)

print('After Transformation(Encoding)- school_state')
print(X_train_school_state.shape)
print(X_test_school_state.shape)
print(X_cv_school_state.shape)





##################################################
#Encoding 'project_grade_category'
vectorizor_pgc=  CountVectorizer()
vectorizor_pgc.fit(X_train['project_grade_category'].values)  #has fit on train data only

#tranforming train, test, cv
X_train_pgc = vectorizor_pgc.transform(X_train['project_grade_category'].values)
X_test_pgc = vectorizor_pgc.transform(X_test['project_grade_category'].values)
X_cv_pgc = vectorizor_pgc.transform(X_cv['project_grade_category'].values)

print('After Transformation(Encoding)- project_grade_category-pgc')
print(X_train_pgc.shape)
print(X_test_pgc.shape)
print(X_cv_pgc.shape)

      
      
      
      
##################################################
#Encoding 'project_subject_categories'- [psc]
vectorizor_psc=  CountVectorizer()
vectorizor_psc.fit(X_train['project_subject_categories'].values)  #has fit on train data only

#tranforming train, test, cv
X_train_psc = vectorizor_psc.transform(X_train['project_subject_categories'].values)
X_test_psc = vectorizor_psc.transform(X_test['project_subject_categories'].values)
X_cv_psc = vectorizor_psc.transform(X_cv['project_subject_categories'].values)

print('After Transformation(Encoding)- project_subject_categories-psc')
print(X_train_psc.shape)
print(X_test_psc.shape)
print(X_cv_psc.shape)
      
      
      
      
###################################################
#Encoding 'project_subject_subcategories'- [pssc]
vectorizor_pssc=  CountVectorizer()
vectorizor_pssc.fit(X_train['project_subject_subcategories'].values)  #has fit on train data only

#tranforming train, test, cv
X_train_pssc = vectorizor_pssc.transform(X_train['project_subject_subcategories'].values)
X_test_pssc = vectorizor_pssc.transform(X_test['project_subject_subcategories'].values)
X_cv_pssc = vectorizor_pssc.transform(X_cv['project_subject_subcategories'].values)

print('After Transformation(Encoding)- project_subject_subcategories  pssc')
print(X_train_pssc.shape)
print(X_test_pssc.shape)
print(X_cv_pssc.shape)

After Transformation(Encoding)- teacher_prefix
(36330, 5)
(13110, 5)
(9177, 5)
After Transformation(Encoding)- school_state
(36330, 51)
(13110, 51)
(9177, 51)
After Transformation(Encoding)- project_grade_category-pgc
(36330, 4)
(13110, 4)
(9177, 4)
After Transformation(Encoding)- project_subject_categories-psc
(36330, 49)
(13110, 49)
(9177, 49)
After Transformation(Encoding)- project_subject_subcategories  pssc
(36330, 333)
(13110, 333)
(9177, 333)

<h3 style="color:#C00000;"> 3.3 Text Featurization </h3>

In [13]:
#1. Getting text column, [Except: id]
def get_text_features(df):
    txt_cols = []
    for col in df.columns:
        if df[col].nunique() >401 and df[col].dtype == 'O':
            txt_cols.append(col)
    return txt_cols
        
txt_cols = get_text_features(X_train)
print(txt_cols)
txt_cols.pop(0)
print(txt_cols)

['id', 'cleaned_titles', 'cleaned_essays', 'cleaned_summary']
['cleaned_titles', 'cleaned_essays', 'cleaned_summary']

In [17]:
#2 checking null values one by one and imputing: missing value as info
d= X_cv   #chenge for all
a= txt_cols[0]
print("In Null in ",a,":", d[a].isnull().sum())
print("Cardinality ",a,":", d[a].nunique())
print(d[a])


#imputing: missing value-as info
if d[a].isnull().sum()>0:
    d[a]= d[a].fillna('Unavilable')
    print('Imputed')
else:
    print('no null values')

In Null in  cleaned_titles : 2
Cardinality  cleaned_titles : 8666
76317                let start reading revolution
11921                    growing readers students
41112    exploring algebra 2 graphing calculators
25090                                cleaning act
56048                          inclusive learning
                           ...
82897                                         put
41749                   literacy center materials
40097                 programming help ipad minis
50107                      headphones right heart
23954                       get flashy technology
Name: cleaned_titles, Length: 9177, dtype: object
Imputed

<b> Observed that df['cleaned_summary'] need some preprocessings </b>

In [18]:
import re 
def replace_underscores(text):
    return re.sub(r'_', ' ', text)

X_train['cleaned_summary']= X_train['cleaned_summary'].apply(replace_underscores)
X_test['cleaned_summary']= X_test['cleaned_summary'].apply(replace_underscores)
X_cv['cleaned_summary']= X_cv['cleaned_summary'].apply(replace_underscores)

print(X_train.shape)
X_train.head(2)

(36330, 13)

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
0,p069249,mrs,ky,grades_prek_2,appliedlearning,earlydevelopment,1,413.00,4,nap day keeps doctor away,hunter hills elementary highest poverty level ...,students need 20 sheets blankets rest time cots,1
1,p257116,mrs,fl,grades_3_5,literacy_language,literature_writing,2,280.35,30,projects 3rd grade olympians,students enthusiastic learning eager come scho...,students need supplies completing classroom pr...,0

<h3 style="color:#C00000;"> 3.3 [A] Bag of Words (All text features) </h3>

In [19]:
X_train['cleaned_titles'].isnull().sum()

0

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer for 'cleaned_titles'
vectorizer_titles = CountVectorizer(min_df=5, max_features=3000)
vectorizer_titles.fit(X_train['cleaned_titles'])  # Fit only on the training data

# Transform the 'cleaned_titles' column in train, test, and cv sets
X_train_title_bow = vectorizer_titles.transform(X_train['cleaned_titles'].values)
X_test_title_bow = vectorizer_titles.transform(X_test['cleaned_titles'].values)
X_cv_title_bow = vectorizer_titles.transform(X_cv['cleaned_titles'].values)

# Print the shapes of the transformed data
print("After Vectorization:")
print("X_train_title_bow shape:", X_train_title_bow.shape)
print("X_test_title_bow shape:", X_test_title_bow.shape)
print("X_cv_title_bow shape:", X_cv_title_bow.shape)

After Vectorization:
X_train_title_bow shape: (36330, 2913)
X_test_title_bow shape: (13110, 2913)
X_cv_title_bow shape: (9177, 2913)

In [21]:
#2.Bow: Project essay
#'cleaned_essays'/ ['cleaned_titles', 'cleaned_essays', 'cleaned_summary']
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer_essay = CountVectorizer(min_df=10, max_features=5000)
vectorizer_essay.fit(X_train['cleaned_essays'])    #fit has happned only on train data

X_train_essays_bow= vectorizer_essay.transform(X_train['cleaned_essays'].values)
X_test_essays_bow= vectorizer_essay.transform(X_test['cleaned_essays'].values)
X_cv_essays_bow= vectorizer_essay.transform(X_cv['cleaned_essays'].values)


print("After Vectorization")
print("X_train_essays_bow shape:", X_train_essays_bow.shape)
print("X_test_essays_bow shape:", X_test_essays_bow.shape)
print("X_cv_essays_bow shape:", X_cv_essays_bow.shape)

After Vectorization
X_train_essays_bow shape: (36330, 5000)
X_test_essays_bow shape: (13110, 5000)
X_cv_essays_bow shape: (9177, 5000)

In [22]:
#3.Bow: 'cleaned_summary'
#'cleaned_summary'/ ['cleaned_titles', 'cleaned_essays', 'cleaned_summary']
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer 
vectorizer_summary = CountVectorizer(min_df=5, max_features=2500)
vectorizer_summary.fit(X_train['cleaned_summary'])    #fit has happned only on train data


X_train_summary_bow= vectorizer_summary.transform(X_train['cleaned_summary'].values)
X_test_summary_bow= vectorizer_summary.transform(X_test['cleaned_summary'].values)
X_cv_summary_bow= vectorizer_summary.transform(X_cv['cleaned_summary'].values)


print("After Vectorization")
print("X_train_summary_bow shape:", X_train_summary_bow.shape)
print("X_test_summary_bow shape:", X_test_summary_bow.shape)
print("X_cv_summary_bow shape:", X_cv_summary_bow.shape)

After Vectorization
X_train_summary_bow shape: (36330, 2500)
X_test_summary_bow shape: (13110, 2500)
X_cv_summary_bow shape: (9177, 2500)

<h3 style="color:#C00000;"> 3.3 [B] tf-idf Vectorizor (All text features) </h3>

In [23]:
#1.Tf-idf: Project titles
#'cleaned_titles'/ ['cleaned_titles', 'cleaned_essays', 'cleaned_summary']
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the CountVectorizer for 
vectorizer_titles = TfidfVectorizer(min_df=5)
vectorizer_titles.fit(X_train['cleaned_titles'])    #fit has happned only on train data

X_train_title_tfidf= vectorizer_titles.transform(X_train['cleaned_titles'].values)
X_test_title_tfidf= vectorizer_titles.transform(X_test['cleaned_titles'].values)
X_cv_title_tfidf= vectorizer_titles.transform(X_cv['cleaned_titles'].values)


print("After Vectorization")
print("X_train_title_tfidf shape:", X_train_title_tfidf.shape)
print("X_test_title_tfidf shape:", X_test_title_tfidf.shape)
print("X_cv_title_tfidf shape:", X_cv_title_tfidf.shape)

After Vectorization
X_train_title_tfidf shape: (36330, 2913)
X_test_title_tfidf shape: (13110, 2913)
X_cv_title_tfidf shape: (9177, 2913)

In [97]:
#2.Tfidf: Project essay
#'cleaned_essays'/ ['cleaned_titles', 'cleaned_essays', 'cleaned_summary']
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the CountVectorizer
vectorizer_essay = TfidfVectorizer(min_df=10, max_features=5000,ngram_range=(1, 2))
vectorizer_essay.fit(X_train['cleaned_essays'])    #fit has happned only on train data

X_train_essays_tfidf= vectorizer_essay.transform(X_train['cleaned_essays'].values)
X_test_essays_tfidf= vectorizer_essay.transform(X_test['cleaned_essays'].values)
X_cv_essays_tfidf= vectorizer_essay.transform(X_cv['cleaned_essays'].values)


print("After Vectorization")
print("X_train_essays_tfidfshape:", X_train_essays_tfidf.shape)
print("X_test_essays_tfidf shape:", X_test_essays_tfidf.shape)
print("X_cv_essays_tfidf shape:", X_cv_essays_tfidf.shape)

After Vectorization
X_train_essays_tfidfshape: (36330, 5000)
X_test_essays_tfidf shape: (13110, 5000)
X_cv_essays_tfidf shape: (9177, 5000)

In [96]:
#3.tf-idf: 'cleaned_summary'
#'cleaned_summary'/ ['cleaned_titles', 'cleaned_essays', 'cleaned_summary']
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the CountVectorizer 
vectorizer_summary = TfidfVectorizer(min_df=10, max_features=5000,ngram_range=(1, 2))
vectorizer_summary.fit(X_train['cleaned_summary'])    #fit has happned only on train data


X_train_summary_tfidf= vectorizer_summary.transform(X_train['cleaned_summary'].values)
X_test_summary_tfidf= vectorizer_summary.transform(X_test['cleaned_summary'].values)
X_cv_summary_tfidf= vectorizer_summary.transform(X_cv['cleaned_summary'].values)


print("After Vectorization")
print("X_train_summary_tfidf shape:", X_train_summary_tfidf.shape)
print("X_test_summary_tfidf shape:", X_test_summary_tfidf.shape)
print("X_cv_summary_tfidf shape:", X_cv_summary_tfidf.shape)

After Vectorization
X_train_summary_tfidf shape: (36330, 5000)
X_test_summary_tfidf shape: (13110, 5000)
X_cv_summary_tfidf shape: (9177, 5000)

<div style="color:#FFFFFF;background-color:Red;text-align:center;padding-top: 50px; padding-right: 30px; padding-bottom: 50px; padding-left: 80px;border-radius:10px 10px 10px 10px;">
    <h1>
        4. [Assignment 5] Logistic Regression-Donor Choose Dataset 
    </h1>
</div>

<b> Logistic Regression(either SGDClassifier with log loss) on these feature sets</b>

- Set 1: categorical, numerical features + project_title(BOW) + preprocessed_eassay (`BOW with bi-grams` with `min_df=10` and `max_features=5000`)
- Set 2: categorical, numerical features + project_title(TFIDF)+ preprocessed_eassay (`TFIDF with bi-grams` with `min_df=10` and `max_features=5000`)
- Set 3: categorical, numerical features + project_title(AVG W2V)+ preprocessed_eassay (AVG W2V)
- Set 4: categorical, numerical features + project_title(TFIDF W2V)+ preprocessed_essay (TFIDF W2V)

<b> Consider these set of features Set 5 :</b>
- school_state : categorical data
- clean_categories : categorical data
- clean_subcategories : categorical data
- project_grade_category :categorical data
- teacher_prefix : categorical data
- quantity : numerical data
- teacher_number_of_previously_posted_projects : numerical data
- price : numerical data
- sentiment score's of each of the essay : numerical data
- number of words in the title : numerical data
- number of words in the combine essays : numerical data

In [33]:
# Set 1: categorical, numerical features + project_title(BOW) + preprocessed_essay (BOW)


#numarical_features
from scipy.sparse import hstack, csr_matrix
X_train_numcol = csr_matrix(X_train[['teacher_number_of_previously_posted_projects', 'price', 'quantity', 'isdigit_summary']])
X_test_numcol  = csr_matrix(X_test[['teacher_number_of_previously_posted_projects', 'price', 'quantity', 'isdigit_summary']])
X_cv_numcol    = csr_matrix(X_cv[['teacher_number_of_previously_posted_projects', 'price', 'quantity', 'isdigit_summary']])

print('numarical_features')
print(X_train_numcol.shape)
print(X_test_numcol.shape)
print(X_cv_numcol.shape)




#################################################
#combining all categrorical features encoded
from scipy.sparse import hstack

# Combine all the vectorized features
X_train_cat_combined = hstack([X_train_teacher_prefix, X_train_school_state, X_train_pgc, X_train_psc, X_train_pssc])
X_test_cat_combined = hstack([X_test_teacher_prefix, X_test_school_state, X_test_pgc, X_test_psc, X_test_pssc])
X_cv_cat_combined = hstack([X_cv_teacher_prefix, X_cv_school_state, X_cv_pgc, X_cv_psc, X_cv_pssc])

print('categrorical features')
print(X_train_cat_combined.shape)
print(X_test_cat_combined.shape)
print(X_cv_cat_combined.shape)

numarical_features
(36330, 4)
(13110, 4)
(9177, 4)
categrorical features
(36330, 442)
(13110, 442)
(9177, 442)

<h4 style="color:#C00000;"> Set 1: categorical, numerical features + project_title(BOW) + preprocessed_eassay (BOW with bi-grams with min_df=10 and max_features=5000)</h4>

In [34]:
# X_train now have all the categorical, numarical data
#Now need to 1) project_title(BOW); 2), preprocessed_essay (BOW)

# merge two sparse matrices: https://stackoverflow.com/a/19710648/4084039
from scipy.sparse import hstack
# with the same hstack function we are concatinating a sparse matrix and a dense matirx :)
# X = hstack((categories_one_hot, sub_categories_one_hot, text_bow, price_standardized))
# X.shape


## Set 1: categorical, numerical features + project_title(BOW) + preprocessed_essay (BOW)
X_train1= hstack((X_train_numcol, X_train_cat_combined, X_train_title_bow, X_train_essays_bow)).tocsr()        #train
X_cv1= hstack((X_cv_numcol, X_cv_cat_combined,X_cv_title_bow, X_cv_essays_bow)).tocsr()                        #cv
X_test1= hstack((X_test_numcol, X_test_cat_combined,X_test_title_bow, X_test_essays_bow)).tocsr()              #test



print("Train:", X_train1.shape, y_train.shape)
print("Cr_val:",X_cv1.shape, y_cv.shape)
print("Test:",X_test1.shape, y_test.shape)

Train: (36330, 8359) (36330,)
Cr_val: (9177, 8359) (9177,)
Test: (13110, 8359) (13110,)

In [99]:
#Trying with default parameters
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


clf= LogisticRegression(solver= 'liblinear', max_iter=2000, C=100, penalty='l1')
clf.fit(X_train1,y_train)

# Prediction
y_pred = clf.predict(X_test1)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.7418001525553013
Classification Report:
              precision    recall  f1-score   support

           0       0.23      0.31      0.26      1955
           1       0.87      0.82      0.84     11155

    accuracy                           0.74     13110
   macro avg       0.55      0.56      0.55     13110
weighted avg       0.78      0.74      0.76     13110

Confusion Matrix:
[[ 607 1348]
 [2037 9118]]

In [100]:
#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html

<h4 style="color:red"> Set 2: categorical, numerical features + project_title(TFIDF)+ preprocessed_eassay (TFIDF with bi-grams with min_df=10 and max_features=5000)</h4>

In [102]:
#set2: data
from scipy.sparse import hstack

## Set 2: categorical, numerical features + project_title(Tfidf) + preprocessed_essay (Tfidf)
X_train2= hstack((X_train_numcol, X_train_cat_combined, X_train_title_tfidf, X_train_essays_tfidf)).tocsr()        #train
X_cv2= hstack((X_cv_numcol, X_cv_cat_combined,X_cv_title_tfidf, X_cv_essays_tfidf)).tocsr()                        #cv
X_test2= hstack((X_test_numcol, X_test_cat_combined,X_test_title_tfidf, X_test_essays_tfidf)).tocsr()              #test



print("Train:", X_train2.shape, y_train.shape)
print("Cr_val:",X_cv2.shape, y_cv.shape)
print("Test:",X_test2.shape, y_test.shape)

Train: (36330, 8359) (36330,)
Cr_val: (9177, 8359) (9177,)
Test: (13110, 8359) (13110,)

In [ ]:
#Trying with default parameters
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


clf= LogisticRegression(solver= 'liblinear', max_iter=2000, C=100, penalty='l1')
clf.fit(X_train2,y_train)

# Prediction
y_pred = clf.predict(X_test2)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)